// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQd2QOvwLY8ul5ip-BE7laqACcC0AjKxU',
    appId: '1:130003660816:web:3689e5b173cfbaf92f9a95',
    messagingSenderId: '130003660816',
    projectId: 'educare-mobile-40f4a',
    authDomain: 'educare-mobile-40f4a.firebaseapp.com',
    storageBucket: 'educare-mobile-40f4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE31zZ1Sy-PVtBNiwdp8FZIS61nYYKMs0',
    appId: '1:130003660816:android:2d801a06e3aabf702f9a95',
    messagingSenderId: '130003660816',
    projectId: 'educare-mobile-40f4a',
    storageBucket: 'educare-mobile-40f4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIlzvIXJE-so4ah8d8YfVsgyYGhKjOZgw',
    appId: '1:130003660816:ios:c30b812da0c223f72f9a95',
    messagingSenderId: '130003660816',
    projectId: 'educare-mobile-40f4a',
    storageBucket: 'educare-mobile-40f4a.appspot.com',
    iosBundleId: 'com.example.emrMApp',
  );
}
